//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "profile")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub name: String,
    pub height: i16,
    pub cost_per_hour: i16,
    pub description: String,
    pub phone_number: String,
    pub city: String,
    pub region: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::profile_photo::Entity")]
    ProfilePhoto,
}

impl Related<super::profile_photo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfilePhoto.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
